name: react-template
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          npm ci
          npm run build:github
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.DEPLOY }}
          branch: gh-pages
          folder: dist
